wrapperVersion={{WRAPPER_VERSION}}
distributionType=only-script
distributionUrl=https://repo.maven.apache.org/maven2/org/apache/maven/apache-maven/{{MAVEN_VERSION}}/apache-maven-{{MAVEN_VERSION}}-bin.zip
distributionSha256Sum={{MAVEN_SHA256}}
